[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Disable automatic plugin detection
[build.processing]
  skip_processing = false

# Explicitly disable Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    skip = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run web"
  port = 8080
  publish = "dist"
